export const SET_STUDENTS = 'SET_STUDENTS'
export const SET_STUDENTS_FAILURE = 'SET_STUDENTS_FAILURE'

export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE'

export const SET_STUDENT_IMAGE = 'SET_STUDENT_IMAGE'
export const SET_STUDENT_IMAGE_FAILURE = 'SET_STUDENT_IMAGE_FAILURE'

export const ADD_EVENT = 'ADD_EVENT'
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE'

export const REMOVE_EVENT = 'REMOVE_EVENT'
export const REMOVE_EVENT_FAILURE = 'REMOVE_EVENT_FAILURE'

export const SET_EVENTS = 'SET_EVENTS'
export const SET_EVENTS_FAILURE = 'SET_EVENTS_FAILURE'

export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT'
export const SET_CURRENT_EVENT_FAILURE = 'SET_CURRENT_EVENT_FAILURE'

export const ADD_STUDENT_TO_EVENT = 'ADD_STUDENT_TO_EVENT'
export const ADD_STUDENT_TO_EVENT_FAILURE = 'ADD_STUDENT_TO_EVENT_FAILURE'

export const REMOVE_STUDENT_FROM_EVENT = 'REMOVE_STUDENT_FROM_EVENT'
export const REMOVE_STUDENT_FROM_EVENT_FAILURE = 'REMOVE_STUDENT_FROM_EVENT_FAILURE'
export const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT'

export const COMPLETE_EVENT = 'COMPLETE_EVENT'
export const COMPLETE_EVENT_FAILURE = 'COMPLETE_EVENT_FAILURE'

export const SET_READER_STATUS = 'SET_READER_STATUS'
export const SET_CARD_STATUS = 'SET_CARD_STATUS'
export const SET_CARD_ATR = 'SET_CARD_ATR'

export const PUSH_ROUTE_STACK = 'PUSH_ROUTE_STACK'
export const POP_ROUTE_STACK = 'POP_ROUTE_STACK'

export const AUTHENTICATION = 'AUTHENTICATION'
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION'
export const POP_NOTIFICATION = 'POP_NOTIFICATION'
