export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_ALL_EVENTS = 'SET_ALL_EVENTS'
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT'
export const PATCH_CURRENT_EVENT = 'PATCH_CURRENT_EVENT'

export const ADD_TO_LOCAL_EVENTS = 'ADD_TO_LOCAL_EVENTS'
export const REMOVE_FROM_LOCAL_EVENTS = 'REMOVE_FROM_LOCAL_EVENTS'
export const REMOVE_LOCAL_EVENTS = 'REMOVE_LOCAL_EVENTS'
export const SET_LOCAL_EVENTS = 'SET_LOCAL_EVENTS'

export const SET_ALL_STUDENTS = 'SET_ALL_STUDENTS'
export const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT'
export const PATCH_CURRENT_STUDENT = 'PATCH_CURRENT_STUDENT'

export const ADD_EVENT_RECORD = 'ADD_EVENT_RECORD'

export const SET_OFFLINE = 'SET_OFFLINE'
export const ADD_CONSISTENCY = 'ADD_CONSISTENCY'
export const CLEAR_CONSISTENCY = 'CLEAR_CONSISTENCY'

export const APPEND_BROKEN_EVENT = 'APPEND_BROKEN_EVENT'
export const SET_BROKEN_EVENTS = 'SET_BROKEN_EVENTS'
// export const SET_CURRENT_EVENT_NAME = 'SET_CURRENT_EVENT_NAME'
// export const SET_CURRENT_EVENT_TIME = 'SET_CURRENT_EVENT_TIME'
// export const SET_CURRENT_EVENT_DESCRIPTION = 'SET_CURRENT_EVENT_DESCRIPTION'
// export const SET_CURRENT_EVENT_STATUS = 'SET_CURRENT_EVENT_STATUS'

